#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-private"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "6b48ac2874e64f7d8202388c50a285c3" }
]

[assets]
directory = "./public"
